services:
  unraid-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unraid-mcp
    restart: unless-stopped
    ports:
      # HostPort:ContainerPort (maps to UNRAID_MCP_PORT inside the container, default 6970)
      # Change the host port (left side) if 6970 is already in use on your host
      - "6970:6970" 
    env_file:
      - .env # Loads environment variables from .env in the same directory as this docker-compose.yml
    # Optional: If you want to mount a specific directory for logs (ensure UNRAID_MCP_LOG_FILE in .env points within this mount)
    # volumes:
    #   - ./logs:/app/logs # Example: maps ./logs on host to /app/logs in container
