# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Set working directory
WORKDIR /app

# Copy requirements and source code
COPY requirements.txt ./
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose any necessary ports, if using SSE (not required for stdio)
# EXPOSE 8000

# Set environment variables
# It is expected that runtime environment variables are passed in through the Docker runtime.

# Set entrypoint command
ENTRYPOINT [ "python", "run_server.py", "stdio" ]
