//! Structural contract between the vendored SDL and a real Unraid machine.
//!
//! `schema/live-introspection.json` is generated by
//! `scripts/live-schema-contract.py`. Descriptions and applied directives are
//! intentionally excluded because standard introspection cannot reproduce all
//! SDL source details; types, fields, arguments, inputs, enums, interfaces,
//! unions, and operation roots are compared exactly.

use std::collections::BTreeMap;

use apollo_compiler::ast::FieldDefinition;
use apollo_compiler::schema::ExtendedType;
use apollo_compiler::Schema;
use serde_json::{json, Map, Value};

const SCHEMA_SDL: &str = include_str!("../schema/unraid-schema.graphql");
const LIVE_CONTRACT: &str = include_str!("../schema/live-introspection.json");

fn field_contract(field: &FieldDefinition) -> Value {
    let args = field
        .arguments
        .iter()
        .map(|arg| {
            (
                arg.name.as_str().to_owned(),
                Value::String(arg.ty.to_string()),
            )
        })
        .collect::<BTreeMap<_, _>>();
    json!({
        "type": field.ty.to_string(),
        "args": args,
    })
}

fn sdl_contract() -> Value {
    let schema = Schema::parse_and_validate(SCHEMA_SDL, "unraid-schema.graphql")
        .unwrap_or_else(|error| panic!("vendored SDL must be valid:\n{}", error.errors));

    let mut types = Map::new();
    for (name, definition) in &schema.types {
        if name.as_str().starts_with("__") {
            continue;
        }

        let contract = match definition {
            ExtendedType::Scalar(_) => json!({"kind": "SCALAR"}),
            ExtendedType::Object(object) => {
                let fields = object
                    .fields
                    .iter()
                    .map(|(name, field)| (name.as_str().to_owned(), field_contract(field)))
                    .collect::<BTreeMap<_, _>>();
                let mut interfaces = object
                    .implements_interfaces
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>();
                interfaces.sort();
                json!({
                    "kind": "OBJECT",
                    "fields": fields,
                    "interfaces": interfaces,
                })
            }
            ExtendedType::Interface(interface) => {
                let fields = interface
                    .fields
                    .iter()
                    .map(|(name, field)| (name.as_str().to_owned(), field_contract(field)))
                    .collect::<BTreeMap<_, _>>();
                let mut interfaces = interface
                    .implements_interfaces
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>();
                interfaces.sort();
                json!({
                    "kind": "INTERFACE",
                    "fields": fields,
                    "interfaces": interfaces,
                })
            }
            ExtendedType::Union(union) => {
                let mut possible_types = union
                    .members
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>();
                possible_types.sort();
                json!({
                    "kind": "UNION",
                    "possible_types": possible_types,
                })
            }
            ExtendedType::Enum(enum_type) => {
                let mut values = enum_type
                    .values
                    .keys()
                    .map(|name| name.as_str())
                    .collect::<Vec<_>>();
                values.sort();
                json!({
                    "kind": "ENUM",
                    "enum_values": values,
                })
            }
            ExtendedType::InputObject(input) => {
                let fields = input
                    .fields
                    .iter()
                    .map(|(name, field)| {
                        (
                            name.as_str().to_owned(),
                            Value::String(field.ty.to_string()),
                        )
                    })
                    .collect::<BTreeMap<_, _>>();
                json!({
                    "kind": "INPUT_OBJECT",
                    "input_fields": fields,
                })
            }
        };
        types.insert(name.as_str().to_owned(), contract);
    }

    json!({
        "roots": {
            "queryType": schema.schema_definition.query.as_ref().map(ToString::to_string),
            "mutationType": schema.schema_definition.mutation.as_ref().map(ToString::to_string),
            "subscriptionType": schema.schema_definition.subscription.as_ref().map(ToString::to_string),
        },
        "types": types,
    })
}

fn collect_differences(path: &str, actual: &Value, expected: &Value, out: &mut Vec<String>) {
    match (actual, expected) {
        (Value::Object(actual), Value::Object(expected)) => {
            let keys = actual
                .keys()
                .chain(expected.keys())
                .collect::<std::collections::BTreeSet<_>>();
            for key in keys {
                let child_path = format!("{path}.{key}");
                match (actual.get(key), expected.get(key)) {
                    (Some(actual), Some(expected)) => {
                        collect_differences(&child_path, actual, expected, out)
                    }
                    (Some(actual), None) => {
                        out.push(format!("{child_path}: only in vendored SDL: {actual}"))
                    }
                    (None, Some(expected)) => {
                        out.push(format!("{child_path}: only in live schema: {expected}"))
                    }
                    (None, None) => unreachable!(),
                }
            }
        }
        (Value::Array(actual), Value::Array(expected)) if actual != expected => {
            out.push(format!(
                "{path}: vendored SDL={actual:?}, live schema={expected:?}"
            ));
        }
        _ if actual != expected => {
            out.push(format!(
                "{path}: vendored SDL={actual}, live schema={expected}"
            ));
        }
        _ => {}
    }
}

#[test]
fn vendored_sdl_matches_live_unraid_introspection() {
    let live: Value = serde_json::from_str(LIVE_CONTRACT)
        .expect("live introspection snapshot must be valid JSON");
    let expected = json!({
        "roots": live["roots"],
        "types": live["types"],
    });
    let actual = sdl_contract();
    let mut differences = Vec::new();
    collect_differences("$", &actual, &expected, &mut differences);
    assert!(
        differences.is_empty(),
        "vendored SDL differs from schema/live-introspection.json:\n{}",
        differences.join("\n")
    );
}
