//! Structural compatibility contract between the vendored SDL and a real
//! Unraid machine.
//!
//! `schema/live-introspection.json` is generated by
//! `scripts/live-schema-contract.py`. Descriptions and applied directives are
//! intentionally excluded because standard introspection cannot reproduce all
//! SDL source details. Every vendored type, field, argument, input, enum value,
//! interface, union member, and operation root must exist unchanged in the live
//! schema. Live-only extensions are allowed because Unraid plugins can extend
//! the server schema without changing the published upstream SDL.

use std::collections::BTreeMap;

use apollo_compiler::ast::FieldDefinition;
use apollo_compiler::schema::ExtendedType;
use apollo_compiler::Schema;
use serde_json::{json, Map, Value};

const SCHEMA_SDL: &str = include_str!("../schema/unraid-schema.graphql");
const LIVE_CONTRACT: &str = include_str!("../schema/live-introspection.json");

fn field_contract(field: &FieldDefinition) -> Value {
    let args = field
        .arguments
        .iter()
        .map(|arg| {
            (
                arg.name.as_str().to_owned(),
                Value::String(arg.ty.to_string()),
            )
        })
        .collect::<BTreeMap<_, _>>();
    json!({
        "type": field.ty.to_string(),
        "args": args,
    })
}

fn sdl_contract() -> Value {
    let schema = Schema::parse_and_validate(SCHEMA_SDL, "unraid-schema.graphql")
        .unwrap_or_else(|error| panic!("vendored SDL must be valid:\n{}", error.errors));

    let mut types = Map::new();
    for (name, definition) in &schema.types {
        if name.as_str().starts_with("__") {
            continue;
        }

        let contract = match definition {
            ExtendedType::Scalar(_) => json!({"kind": "SCALAR"}),
            ExtendedType::Object(object) => {
                let fields = object
                    .fields
                    .iter()
                    .map(|(name, field)| (name.as_str().to_owned(), field_contract(field)))
                    .collect::<BTreeMap<_, _>>();
                let mut interfaces = object
                    .implements_interfaces
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>();
                interfaces.sort();
                json!({
                    "kind": "OBJECT",
                    "fields": fields,
                    "interfaces": interfaces,
                })
            }
            ExtendedType::Interface(interface) => {
                let fields = interface
                    .fields
                    .iter()
                    .map(|(name, field)| (name.as_str().to_owned(), field_contract(field)))
                    .collect::<BTreeMap<_, _>>();
                let mut interfaces = interface
                    .implements_interfaces
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>();
                interfaces.sort();
                json!({
                    "kind": "INTERFACE",
                    "fields": fields,
                    "interfaces": interfaces,
                })
            }
            ExtendedType::Union(union) => {
                let mut possible_types = union
                    .members
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>();
                possible_types.sort();
                json!({
                    "kind": "UNION",
                    "possible_types": possible_types,
                })
            }
            ExtendedType::Enum(enum_type) => {
                let mut values = enum_type
                    .values
                    .keys()
                    .map(|name| name.as_str())
                    .collect::<Vec<_>>();
                values.sort();
                json!({
                    "kind": "ENUM",
                    "enum_values": values,
                })
            }
            ExtendedType::InputObject(input) => {
                let fields = input
                    .fields
                    .iter()
                    .map(|(name, field)| {
                        (
                            name.as_str().to_owned(),
                            Value::String(field.ty.to_string()),
                        )
                    })
                    .collect::<BTreeMap<_, _>>();
                json!({
                    "kind": "INPUT_OBJECT",
                    "input_fields": fields,
                })
            }
        };
        types.insert(name.as_str().to_owned(), contract);
    }

    json!({
        "roots": {
            "queryType": schema.schema_definition.query.as_ref().map(ToString::to_string),
            "mutationType": schema.schema_definition.mutation.as_ref().map(ToString::to_string),
            "subscriptionType": schema.schema_definition.subscription.as_ref().map(ToString::to_string),
        },
        "types": types,
    })
}

fn collect_incompatibilities(path: &str, vendored: &Value, live: &Value, out: &mut Vec<String>) {
    match (vendored, live) {
        (Value::Object(vendored), Value::Object(live)) => {
            for (key, vendored_value) in vendored {
                let child_path = format!("{path}.{key}");
                match live.get(key) {
                    Some(live_value) => {
                        collect_incompatibilities(&child_path, vendored_value, live_value, out)
                    }
                    None => out.push(format!(
                        "{child_path}: missing from live schema; vendored SDL={vendored_value}"
                    )),
                }
            }
        }
        (Value::Array(vendored), Value::Array(live)) => {
            let missing = vendored
                .iter()
                .filter(|item| !live.contains(item))
                .collect::<Vec<_>>();
            if !missing.is_empty() {
                out.push(format!(
                    "{path}: values missing from live schema={missing:?}; live schema={live:?}"
                ));
            }
        }
        _ if vendored != live => {
            out.push(format!(
                "{path}: vendored SDL={vendored}, live schema={live}"
            ));
        }
        _ => {}
    }
}

#[test]
fn vendored_sdl_is_compatible_with_live_unraid_introspection() {
    let live: Value = serde_json::from_str(LIVE_CONTRACT)
        .expect("live introspection snapshot must be valid JSON");
    let expected = json!({
        "roots": live["roots"],
        "types": live["types"],
    });
    let actual = sdl_contract();
    let mut incompatibilities = Vec::new();
    collect_incompatibilities("$", &actual, &expected, &mut incompatibilities);
    assert!(
        incompatibilities.is_empty(),
        "vendored SDL is incompatible with schema/live-introspection.json:\n{}",
        incompatibilities.join("\n")
    );
}
