import { describe, it, expect, beforeEach } from "vitest";
import { IncusConfigSyncService } from "./config-sync.service.js";
import type { IncusConfig } from "./config.entity.js";
import type { ConfigService } from "@nestjs/config";
import { mkdtemp, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

// A realistic incus.cfg fixture: comments, blank lines, quoted and
// unquoted values, and an inline trailing comment — the exact shape
// updateShellConfig/parseShellConfig need to round-trip faithfully.
const FIXTURE_CFG = `# Incus plugin configuration
# Generated by the Unraid settings page; safe to hand-edit.

SERVICE="enabled"
INCUS_DIR="/mnt/user/appdata/incus"

# Storage
STORAGE_DRIVER="zfs"
STORAGE_SOURCE='nvme/incus'
STORAGE_POOL_NAME="default"

# Jail networking
JAIL_BRIDGE="agentbr0"
JAIL_SUBNET="198.18.0.1/24" # keep in the RFC 5737-adjacent test range
JAIL_NAT="true"
JAIL_IPV6="none"

# ACL
ACL_NAME="agent-block-lan"
ACL_BLOCK="10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16"
ACL_ALLOW=""
ACL_DEFAULT_EGRESS="allow"
ACL_DEFAULT_INGRESS="drop"

JAIL_PROFILE="agent-jail"
JAIL_IMAGE="images:debian/trixie/cloud"
JAIL_NESTING="false"
JAIL_CPU="2"
JAIL_MEMORY="4GiB"
JAIL_WORKSPACE_ROOT="/srv/agent-jails"
JAIL_AGENT_UID="1000"
JAIL_AGENT_GID="1000"
JAIL_BIND_MOUNTS=""
TS_AUTHKEY=""
`;

function makeService(): IncusConfigSyncService {
  const fakeConfigService = { get: () => undefined, set: () => {} } as unknown as ConfigService;
  return new IncusConfigSyncService(fakeConfigService);
}

describe("parseShellConfig", () => {
  let service: IncusConfigSyncService;

  beforeEach(() => {
    service = makeService();
  });

  it("parses double-quoted values, stripping the quotes", () => {
    const parsed = service.parseShellConfig(FIXTURE_CFG);
    expect(parsed.SERVICE).toBe("enabled");
    expect(parsed.INCUS_DIR).toBe("/mnt/user/appdata/incus");
  });

  it("parses single-quoted values, stripping the quotes", () => {
    const parsed = service.parseShellConfig(FIXTURE_CFG);
    expect(parsed.STORAGE_SOURCE).toBe("nvme/incus");
  });

  it("parses unquoted-looking booleans/numbers as plain strings", () => {
    const parsed = service.parseShellConfig(`JAIL_CPU=2\nJAIL_NAT=true\n`);
    expect(parsed.JAIL_CPU).toBe("2");
    expect(parsed.JAIL_NAT).toBe("true");
  });

  it("strips a trailing inline comment from a quoted value", () => {
    const parsed = service.parseShellConfig(FIXTURE_CFG);
    expect(parsed.JAIL_SUBNET).toBe("198.18.0.1/24");
  });

  it("skips comment-only and blank lines", () => {
    const parsed = service.parseShellConfig(FIXTURE_CFG);
    expect(Object.keys(parsed)).not.toContain("");
    expect(parsed["# Incus plugin configuration"]).toBeUndefined();
  });

  it("parses empty-string values correctly", () => {
    const parsed = service.parseShellConfig(FIXTURE_CFG);
    expect(parsed.ACL_ALLOW).toBe("");
    expect(parsed.JAIL_BIND_MOUNTS).toBe("");
    expect(parsed.TS_AUTHKEY).toBe("");
  });

  it("preserves # inside quoted values while removing a trailing comment", () => {
    const parsed = service.parseShellConfig(`TS_AUTHKEY="abc#def" # actual comment\n`);
    expect(parsed.TS_AUTHKEY).toBe("abc#def");
  });
});

describe("mapShellToTS / shell <-> TS key mapping", () => {
  let service: IncusConfigSyncService;

  beforeEach(() => {
    service = makeService();
  });

  it("maps a representative set of shell variable names to their TS config keys", () => {
    const parsed = service.parseShellConfig(FIXTURE_CFG);
    const mapped = service.mapShellToTS(parsed);

    expect(mapped.jailWorkspaceRoot).toBe("/srv/agent-jails");
    expect(mapped.jailBridge).toBe("agentbr0");
    expect(mapped.storagePoolName).toBe("default");
    expect(mapped.aclName).toBe("agent-block-lan");
    expect(mapped.tsAuthKey).toBe("");
  });

  it("maps SERVICE=enabled/disabled to the boolean `enabled` field", () => {
    expect(service.mapShellToTS({ SERVICE: "enabled" }).enabled).toBe(true);
    expect(service.mapShellToTS({ SERVICE: "disabled" }).enabled).toBe(false);
  });

  it("maps JAIL_NAT/JAIL_NESTING true/false strings to booleans", () => {
    const mapped = service.mapShellToTS({ JAIL_NAT: "true", JAIL_NESTING: "false" });
    expect(mapped.jailNat).toBe(true);
    expect(mapped.jailNesting).toBe(false);
  });

  it("round-trips the shell -> TS key mapping symmetrically via updateShellConfig's keyMap", () => {
    // Cross-check a handful of mappings hold in both directions: parse the
    // fixture, take the mapped TS value, write it back out via
    // updateShellConfig, and confirm the same shell key received the
    // (re-encoded) value — i.e. the two directions agree on which shell key
    // corresponds to which TS key.
    const parsed = service.parseShellConfig(FIXTURE_CFG);
    const mapped = service.mapShellToTS(parsed);

    const updated = service.updateShellConfig(FIXTURE_CFG, { jailWorkspaceRoot: "/srv/agent-jails" });
    expect(updated).toMatch(/JAIL_WORKSPACE_ROOT='\/srv\/agent-jails'/);

    const updatedAcl = service.updateShellConfig(FIXTURE_CFG, { aclName: mapped.aclName });
    expect(updatedAcl).toMatch(/ACL_NAME='agent-block-lan'/);
  });
});

describe("updateShellConfig round trip", () => {
  let service: IncusConfigSyncService;

  beforeEach(() => {
    service = makeService();
  });

  it("changes only the targeted field's value, leaving every other line byte-identical", () => {
    const updated = service.updateShellConfig(FIXTURE_CFG, { jailCpu: "4" });
    const originalLines = FIXTURE_CFG.split("\n");
    const updatedLines = updated.split("\n");

    expect(updatedLines).toHaveLength(originalLines.length);

    let changedLines = 0;
    for (let i = 0; i < originalLines.length; i++) {
      if (originalLines[i] !== updatedLines[i]) {
        changedLines++;
        expect(originalLines[i]).toMatch(/^JAIL_CPU=/);
        expect(updatedLines[i]).toBe(`JAIL_CPU='4'`);
      }
    }
    expect(changedLines).toBe(1);
  });

  it("preserves comment-only lines and blank lines verbatim", () => {
    const updated = service.updateShellConfig(FIXTURE_CFG, { jailCpu: "4" });
    expect(updated).toContain("# Incus plugin configuration");
    expect(updated).toContain("# Storage");
    expect(updated).toContain("# Jail networking");
    // blank line count preserved
    const originalBlank = FIXTURE_CFG.split("\n").filter((l) => l.trim() === "").length;
    const updatedBlank = updated.split("\n").filter((l) => l.trim() === "").length;
    expect(updatedBlank).toBe(originalBlank);
  });

  it("preserves a trailing inline comment on the updated line", () => {
    const updated = service.updateShellConfig(FIXTURE_CFG, { jailSubnet: "198.18.0.1/25" });
    expect(updated).toContain("JAIL_SUBNET='198.18.0.1/25' # keep in the RFC 5737-adjacent test range");
  });

  it("does not mistake # inside an existing quoted value for a comment", () => {
    const updated = service.updateShellConfig(`TS_AUTHKEY='old#value' # keep\n`, { tsAuthKey: "new" });
    expect(updated).toBe(`TS_AUTHKEY='new' # keep\n`);
  });

  it("always emits single-quoted output regardless of original quoting style", () => {
    // STORAGE_SOURCE was originally single-quoted; INCUS_DIR was double-quoted.
    const updated = service.updateShellConfig(FIXTURE_CFG, {
      storageSource: "nvme/incus2",
      stateDir: "/mnt/user/appdata/incus2",
    });
    expect(updated).toContain("STORAGE_SOURCE='nvme/incus2'");
    expect(updated).toContain("INCUS_DIR='/mnt/user/appdata/incus2'");
  });

  it("converts booleans back to enabled/disabled and true/false correctly", () => {
    const updated = service.updateShellConfig(FIXTURE_CFG, { enabled: false, jailNat: false, jailNesting: true });
    expect(updated).toContain("SERVICE='disabled'");
    expect(updated).toContain("JAIL_NAT='false'");
    expect(updated).toContain("JAIL_NESTING='true'");
  });

  it("full round trip: parse -> modify one field -> reserialize -> reparse yields the expected merged config", () => {
    const parsedBefore = service.mapShellToTS(service.parseShellConfig(FIXTURE_CFG));
    const updatedCfg = service.updateShellConfig(FIXTURE_CFG, { jailMemory: "8GiB" });
    const parsedAfter = service.mapShellToTS(service.parseShellConfig(updatedCfg));

    expect(parsedAfter.jailMemory).toBe("8GiB");
    // every other field is unchanged
    const { jailMemory: _before, ...restBefore } = parsedBefore as IncusConfig;
    const { jailMemory: _after, ...restAfter } = parsedAfter as IncusConfig;
    expect(restAfter).toEqual(restBefore);
  });

  it("neutralizes shell metacharacters in a value via single-quoting (no injection on `. $CFG` sourcing)", () => {
    const malicious = `x'; rm -rf /; echo '`;
    const updated = service.updateShellConfig(FIXTURE_CFG, { tsAuthKey: malicious });
    // bash single-quote escaping: close quote, escaped quote, reopen quote
    expect(updated).toContain(`TS_AUTHKEY='x'\\''; rm -rf /; echo '\\'''`);
  });
});

describe("config persistence integration", () => {
  it("writes cfg and JSON atomically with secret-safe permissions", async () => {
    const dir = await mkdtemp(join(tmpdir(), "incus-config-"));
    const cfgPath = join(dir, "incus.cfg");
    const jsonPath = join(dir, "incus.json");
    await writeFile(cfgPath, FIXTURE_CFG, { mode: 0o644 });
    const set = () => undefined;
    const config = { get: () => undefined, set } as unknown as ConfigService;
    const service = new IncusConfigSyncService(config, { cfgPath, jsonPath });
    await service.applyConfigUpdate({ tsAuthKey: "tskey-test", jailCpu: "4" });
    expect((await stat(cfgPath)).mode & 0o777).toBe(0o600);
    expect((await stat(jsonPath)).mode & 0o777).toBe(0o600);
  });
});
