use super::setup::SetupCommand;

/// All CLI subcommands. Each variant maps 1:1 to a service method.
pub enum CliCommand {
    Array,
    Disks,
    Docker,
    DockerLogs {
        id: String,
        tail: Option<i64>,
    },
    Vms,
    Server,
    Info,
    Shares,
    Notifications,
    LogFiles,
    LogFile {
        path: String,
        lines: Option<i64>,
        start_line: Option<i64>,
    },
    Services,
    Network,
    Ups,
    UpsConfig,
    Metrics,
    Plugins,
    ParityHistory,
    Vars,
    Registration,
    Flash,
    Rclone,
    RemoteAccess,
    Connect,
    Online,
    SystemTime,
    InstalledUnraidPlugins,
    IsSsoEnabled,
    PublicOidcProviders,
    OidcProviders,
    OidcConfiguration,
    ApiKeys,
    ApiKeyPossibleRoles,
    ApiKeyPossiblePermissions,
    GetAvailableAuthActions,
    GetApiKeyCreationFormSchema,
    Config,
    Settings,
    Display,
    Customization,
    InternalBootContext,
    Me,
    Owner,
    Servers,
    IsFreshInstall,
    PublicTheme,
    NetworkInterfaces,
    TimeZoneOptions,
    AssignableDisks,
    PluginInstallOperations,
    Cloud,
    ApiKey(String),
    Disk(String),
    OidcProvider(String),
    UpsDeviceById(String),
    PluginInstallOperation(String),
    ValidateOidcSession(String),
    GetPermissionsForRoles(Vec<String>),
    PreviewEffectivePermissions(Option<Vec<String>>),
    RecalculateOverview,
    DeleteArchivedNotifications,
    ArchiveNotification(String),
    CreateNotification {
        title: String,
        subject: String,
        description: String,
        importance: String,
        link: Option<String>,
    },
    VmStart(String),
    VmStop(String),
    VmPause(String),
    VmResume(String),
    VmForceStop(String),
    VmReboot(String),
    VmReset(String),
    DockerStart(String),
    DockerStop(String),
    DockerRestart(String),
    DockerPause(String),
    DockerUnpause(String),
    DockerUpdateContainer(String),
    DockerRemoveContainer(String),
    DockerUpdateContainers(Vec<String>),
    DockerUpdateAllContainers,
    DockerCreateFolder {
        name: String,
        parent_id: Option<String>,
        children_ids: Option<Vec<String>>,
    },
    DockerCreateFolderWithItems {
        name: String,
        parent_id: Option<String>,
        source_entry_ids: Option<Vec<String>>,
        position: Option<f64>,
    },
    DockerSetFolderChildren {
        folder_id: Option<String>,
        children_ids: Vec<String>,
    },
    DockerDeleteEntries(Vec<String>),
    DockerMoveEntriesToFolder {
        source_entry_ids: Vec<String>,
        destination_folder_id: String,
    },
    DockerMoveItemsToPosition {
        source_entry_ids: Vec<String>,
        destination_folder_id: String,
        position: f64,
    },
    DockerRenameFolder {
        folder_id: String,
        new_name: String,
    },
    RefreshDockerDigests,
    ResetDockerTemplateMappings,
    SyncDockerTemplatePaths,
    CustomizationSetLocale(String),
    CustomizationSetTheme(String),
    ArraySetState(String),
    ArrayAddDiskToArray(String),
    ArrayRemoveDiskFromArray(String),
    ArrayMountArrayDisk(String),
    ArrayUnmountArrayDisk(String),
    ArrayClearArrayDiskStatistics(String),
    ParityCheckStart(bool),
    ParityCheckPause,
    ParityCheckResume,
    ParityCheckCancel,
    ApiKeyCreate(String),
    ApiKeyAddRole(String, String),
    ApiKeyRemoveRole(String, String),
    ApiKeyDelete(Vec<String>),
    ApiKeyUpdate(String),
    RcloneCreateRemote(String, String),
    RcloneDeleteRemote(String),
    UnraidPluginsInstallPlugin(String),
    UnraidPluginsInstallLanguage(String),
    OnboardingComplete,
    OnboardingReset,
    OnboardingBypass,
    OnboardingClearOverride,
    OnboardingClose,
    OnboardingOpen,
    OnboardingResume,
    OnboardingRefreshInternalBootContext,
    OnboardingCreateInternalBootPool {
        pool_name: String,
        devices: Vec<String>,
        boot_size_mib: i32,
        update_bios: bool,
        reboot: Option<bool>,
    },
    ArchiveNotifications(Vec<String>),
    UnarchiveNotifications(Vec<String>),
    UnreadNotification(String),
    ArchiveAll(Option<String>),
    UnarchiveAll(Option<String>),
    UpdateServerIdentity(String),
    ConnectSignOut,
    ConnectSignIn(String),
    SetupRemoteAccess {
        access_type: String,
        forward_type: Option<String>,
        port: Option<i32>,
    },
    UpdateApiSettings {
        access_type: Option<String>,
        forward_type: Option<String>,
        port: Option<i32>,
    },
    UpdateSshSettings {
        enabled: bool,
        port: i32,
    },
    InitiateFlashBackup {
        remote_name: String,
        source_path: String,
        destination_path: String,
    },
    NotifyIfUnique {
        title: String,
        subject: String,
        description: String,
        importance: String,
        link: Option<String>,
    },
    Doctor,
    Setup(SetupCommand),
}
